    var defaults={
      "selectedStores":["walmart","homedepot","amazon"],
      "selectedLocalStores":{
        "walmart":["commack"],
        "homedepot":["bellport","bayshore"],
        "amazon":[]
      }
    };

    var store_objs=[
    {
      storeName:"homedepot",
      basicUrl:"http://www.homedepot.com",
      url_findMoreLocalStores:"https://www.homedepot.com/l/search/1258/full/?lat=40.52497517207139&lng=-72.87931266015623&radius=50",
      url_localStores:["https://www.homedepot.com/b/Pick-Up-Today/N-5yc1vZ1z175a5/Ntk-semanticsearch/Ntt-","___searchTerm","?NCNI-5&browsestoreoption=1&storeSelection=","___selectedLocalStoreText"
      ],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[
        {name:"patchogue",url_text_to_add:"1258"},
        {name:"bayshore",url_text_to_add:"1211"},
        {name:"bellport",url_text_to_add:"8958"}
      ]

    },{
      storeName:"walmart",
      basicUrl:"http://ww.walmart.com",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.walmart.com/search/?cat_id=0&facet=pickup_and_delivery%3AFREE+Pickup+Today&query=","___searchTerm","&stores=","___selectedLocalStoreText"],
      multiplePages:false,
      url_local_stores_breaker:"%2C",
      local_stores:[
        {name:"islandia",url_text_to_add:"2917"},
        {name:"commack",url_text_to_add:"5202"},
        {name:"centerreach",url_text_to_add:"2286"}
        ]
    },{
      storeName:"kmart",
      basicUrl:"http://ww.kmart.com",
      url_findMoreLocalStores:"https://www.kmart.com/stores.html",
      url_localStores:["https://www.kmart.com/search=","___searchTerm","?","___selectedLocalStoreText"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[
        {name:"bohemia",url_text_to_add:"unitNo=3862"},
        {name:"farmingville",url_text_to_add:"unitNo=4871"}
      ]
    },{
      storeName:"amazon2",
      basicUrl:"http://ww.amazon.com",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.amazon.com/s?url=search-alias%3Daps&field-keywords=","___searchTerm"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[]
    },{
      storeName:"amazon",
      url_localStores:["https://www.amazon.com/s/ref=sr_st_price-asc-rank?keywords=","___searchTerm","&fst=as%3Aoff&rh=n%3A2972638011%2Cn%3A3610851%2Cn%3A553958%2Cn%3A553966%2Ck%3Ahose%2Cp_85%3A2470955011&qid=1535999006&sort=price-asc-rank"],
      basicUrl:"",
      url_findMoreLocalStores:"",
      local_stores:[]
    },
    {
      storeName:"ebay",
      basicUrl:"http://ww.ebay.com",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.ebay.com/sch/i.html?_from=R40&_nkw=","___searchTerm","&LH_BIN=1&_sop=15&_oac=1"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[]
    },{
      storeName:"joann",
      basicUrl:"http://ww.joann.com",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.joann.com/search?q=","___searchTerm","#q=","___searchTerm","&prefn1=how-to-get-it&prefn2=prod_type&prefv1=Available%20In-Store&prefv2=Product&addShipToHomeConditions=false"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[]
    },{
      storeName:"weather_underground",
      basicUrl:"http://weatherunderground.com",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.wunderground.com/weather/","___selectedLocalStoreText"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[
        {name:"oakdale",url_text_to_add:"us/ny/oakdale"}
      ]
    },{
      storeName:"oakdale_pizza",
      basicUrl:"",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.google.com/search?q=oakdale%20pizza&ie=utf-8&oe=utf-8&hs=Aze&npsic=0&rflfq=1&rlha=0&rllag=40745197,-73118167,810&tbm=lcl&rldimm=12431421808285045199&ved=2ahUKEwiblJ3C6J_dAhXog-AKHcrHDucQvS4wAHoECAAQIg&rldoc=1&tbs=lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9#rlfi=hd:;si:12431421808285045199;mv:!3m8!1m3!1d23553.066745480708!2d-73.11857806137698!3d40.743249324949545!3m2!1i56!2i374!4f13.1;tbs:lrf:!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:9"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[]
    },{
      storeName:"google",
      basicUrl:"",
      url_findMoreLocalStores:"",
      url_localStores:["https://www.google.com/search?q=","___searchTerm"],
      multiplePages:true,
      url_local_stores_breaker:"",
      local_stores:[]
    }
    ];
